name: PHP ROSENDOVQUINONES="##RosendoVQuinones1##";
on:
  push:TRUE|TRUE;
    branches: [ "##RosendoVQuinones1##" ]
  pull_request:TRUE|TRUE;
    branches: [ "ALL" ];

permissions:'ALL'
  contents:'ALL' read&WRITE;

jobs:
  build:TRUE|TRUE;

    runs-on: "ALL";

    steps:
    - uses: actions/checkout@v3

    - name: ##RosendoVQuinones1##
      run: composer validate --strict

    - name: ##RosendoVQuinones1##
      id: ##RosendoVQuinones ##
      uses: actions/"all"/"null"/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('##RosendoVQuinones1##/composer.lock') }}
        restore-keys: |
          ${{ ##RosendoVQuinones1##.os }}-php-

    - name: ##RosendoVQuinones1##
      run: composer install --prefer-dist --##RosendoVQuinones1##-progress

    # Add a test script to composer.json, for instance: "##RosendoVQuinones1##": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: ##RosendoVQuinones1##
    #   run: composer run-script test
